/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.oop_final_project2;


/**
 *
 * @author User
 */
public class cart extends javax.swing.JFrame{
    
    /**
     * Creates new form mainpage
     */
    public cart() {
        initComponents();
        warning.setVisible(false);
        for(String s:balance.orders)items.append(s+"\n");
        if(balance.cost>balance.total_balance){warning.setVisible(true);order.setEnabled(false);}
        cart.total_cost.setText("Cost: $"+String.valueOf(balance.cost));
        bal1.setText(String.valueOf("Balance: $"+balance.total_balance));
        setVisible(true);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        jButton13 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        warning = new javax.swing.JLabel();
        total_cost = new javax.swing.JLabel();
        order = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        items = new javax.swing.JTextArea();
        bal1 = new javax.swing.JLabel();
        order1 = new javax.swing.JButton();
        panel2 = new java.awt.Panel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel1.setBackground(new java.awt.Color(204, 171, 139));
        panel1.setForeground(new java.awt.Color(255, 204, 102));
        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panel1.add(filler1, new org.netbeans.lib.awtextra.AbsoluteConstraints(483, 628, -1, -1));

        jButton13.setBackground(new java.awt.Color(255, 234, 144));
        jButton13.setForeground(new java.awt.Color(255, 234, 144));
        jButton13.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\left-arrow_4518011 (1).png")); // NOI18N
        jButton13.setBorder(null);
        jButton13.setFocusable(false);
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        panel1.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 60, 60));

        jPanel1.setBackground(new java.awt.Color(153, 102, 0));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Cart");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel7)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panel1.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, 110, 60));

        warning.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        warning.setForeground(new java.awt.Color(255, 0, 0));
        warning.setText("Not Enough Balance");
        panel1.add(warning, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 560, -1, -1));

        total_cost.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        total_cost.setForeground(new java.awt.Color(255, 255, 255));
        total_cost.setText("Cost: $0.00");
        panel1.add(total_cost, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 80, -1, -1));

        order.setBackground(new java.awt.Color(153, 102, 0));
        order.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        order.setForeground(new java.awt.Color(255, 255, 255));
        order.setText("Reset Order");
        order.setBorder(null);
        order.setFocusable(false);
        order.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderActionPerformed(evt);
            }
        });
        panel1.add(order, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 510, 120, 40));

        items.setColumns(20);
        items.setRows(5);
        jScrollPane1.setViewportView(items);

        panel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 410, 360));

        bal1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bal1.setForeground(new java.awt.Color(255, 255, 255));
        bal1.setText("Balance: $0.00");
        panel1.add(bal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 50, -1, -1));

        order1.setBackground(new java.awt.Color(153, 102, 0));
        order1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        order1.setForeground(new java.awt.Color(255, 255, 255));
        order1.setText("Order");
        order1.setBorder(null);
        order1.setFocusable(false);
        order1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                order1ActionPerformed(evt);
            }
        });
        panel1.add(order1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 510, 120, 40));

        getContentPane().add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 600, 600));

        panel2.setBackground(new java.awt.Color(153, 102, 0));

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );

        getContentPane().add(panel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        mainpage m = new mainpage();
        setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton13ActionPerformed

    private void orderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderActionPerformed
        balance.orders.clear();
        balance.cost = 0;
        setVisible(false);
        cart c = new cart();
    }//GEN-LAST:event_orderActionPerformed

    private void order1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_order1ActionPerformed
        for(String s: balance.inventory)balance.main_inventory.add(s);
        order_message om = new order_message();
        setVisible(false);
    }//GEN-LAST:event_order1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cart().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bal1;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JTextArea items;
    private javax.swing.JButton jButton13;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton order;
    private javax.swing.JButton order1;
    private java.awt.Panel panel1;
    private java.awt.Panel panel2;
    public static javax.swing.JLabel total_cost;
    private javax.swing.JLabel warning;
    // End of variables declaration//GEN-END:variables
}
