/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.oop_final_project2;

import java.util.ArrayList;




/**
 *
 * @author User
 */
public class fries extends javax.swing.JFrame{

    public fries() {
        initComponents();
        setVisible(true);
        setResizable(false);
        bal.setText(String.valueOf("Balance: $"+balance.total_balance));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        jLabel1 = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        jButton7 = new javax.swing.JButton();
        bal = new javax.swing.JLabel();
        jButton14 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        scroll = new javax.swing.JScrollPane();
        i3 = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        i1 = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        i2 = new javax.swing.JTextPane();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        panel2 = new java.awt.Panel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel1.setBackground(new java.awt.Color(204, 171, 139));
        panel1.setForeground(new java.awt.Color(255, 204, 102));
        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Large: ");
        panel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 370, -1, -1));
        panel1.add(filler1, new org.netbeans.lib.awtextra.AbsoluteConstraints(483, 628, -1, -1));

        jButton7.setBackground(new java.awt.Color(255, 234, 144));
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\french-fries (1).png")); // NOI18N
        jButton7.setBorder(null);
        jButton7.setFocusPainted(false);
        jButton7.setFocusable(false);
        jButton7.setOpaque(true);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        panel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 110, 110));

        bal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bal.setForeground(new java.awt.Color(255, 255, 255));
        bal.setText("Balance: $0.00");
        panel1.add(bal, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, -1, -1));

        jButton14.setBackground(new java.awt.Color(204, 171, 139));
        jButton14.setForeground(new java.awt.Color(255, 234, 144));
        jButton14.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\minus-button (1) (1) (1).png")); // NOI18N
        jButton14.setBorder(null);
        jButton14.setFocusable(false);
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        panel1.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, -1, 20));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Fries");
        panel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 200, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Small: ");
        panel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 310, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Medium: ");
        panel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 340, -1, -1));

        i3.setEditable(false);
        i3.setText("0");
        scroll.setViewportView(i3);

        panel1.add(scroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 370, 60, -1));

        i1.setEditable(false);
        i1.setText("0");
        jScrollPane2.setViewportView(i1);
        i1.getAccessibleContext().setAccessibleName("");

        panel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, 60, -1));

        i2.setEditable(false);
        i2.setText("0");
        jScrollPane3.setViewportView(i2);

        panel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 340, 60, -1));

        jButton15.setBackground(new java.awt.Color(255, 234, 144));
        jButton15.setForeground(new java.awt.Color(255, 234, 144));
        jButton15.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\left-arrow_4518011 (1).png")); // NOI18N
        jButton15.setBorder(null);
        jButton15.setFocusable(false);
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        panel1.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 60, 60));

        jButton16.setBackground(new java.awt.Color(204, 171, 139));
        jButton16.setForeground(new java.awt.Color(255, 234, 144));
        jButton16.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\add (1).png")); // NOI18N
        jButton16.setBorder(null);
        jButton16.setFocusable(false);
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        panel1.add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 370, 20, 20));

        jButton17.setBackground(new java.awt.Color(204, 171, 139));
        jButton17.setForeground(new java.awt.Color(255, 234, 144));
        jButton17.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\add (1).png")); // NOI18N
        jButton17.setBorder(null);
        jButton17.setFocusable(false);
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        panel1.add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 310, 20, 20));

        jButton18.setBackground(new java.awt.Color(204, 171, 139));
        jButton18.setForeground(new java.awt.Color(255, 234, 144));
        jButton18.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\add (1).png")); // NOI18N
        jButton18.setBorder(null);
        jButton18.setFocusable(false);
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        panel1.add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 340, 20, 20));

        jButton19.setBackground(new java.awt.Color(204, 171, 139));
        jButton19.setForeground(new java.awt.Color(255, 234, 144));
        jButton19.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\minus-button (1) (1) (1).png")); // NOI18N
        jButton19.setBorder(null);
        jButton19.setFocusable(false);
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        panel1.add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 370, -1, 20));

        jButton20.setBackground(new java.awt.Color(204, 171, 139));
        jButton20.setForeground(new java.awt.Color(255, 234, 144));
        jButton20.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\minus-button (1) (1) (1).png")); // NOI18N
        jButton20.setBorder(null);
        jButton20.setFocusable(false);
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        panel1.add(jButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, -1, 20));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Small: $2.00");
        panel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Medium: $3.50");
        panel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Large: $6.00");
        panel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, -1, -1));

        jButton1.setBackground(new java.awt.Color(153, 102, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Add to Cart");
        jButton1.setBorder(null);
        jButton1.setFocusable(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        panel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 410, 100, 30));

        getContentPane().add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 460, 530));

        panel2.setBackground(new java.awt.Color(153, 102, 0));

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
        );

        getContentPane().add(panel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
       int n = Integer.parseInt(i1.getText());
        int n2 = n-1;
        if (n2<=0)n2=0;
        String n3 = String.valueOf(n2);
        i1.setText(n3);
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        Foods f = new Foods();
        setVisible(false);
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        int n = Integer.parseInt(i3.getText());
        int n2 = n+1;
        String n3 = String.valueOf(n2);
        i3.setText(n3);
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        int n = Integer.parseInt(i1.getText());
        int n2 = n+1;
        String n3 = String.valueOf(n2);
        i1.setText(n3);
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        int n = Integer.parseInt(i2.getText());
        int n2 = n+1;
        String n3 = String.valueOf(n2);
        i2.setText(n3);
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        int n = Integer.parseInt(i3.getText());
        int n2 = n-1;
        if (n2<=0)n2=0;
        String n3 = String.valueOf(n2);
        i3.setText(n3);
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        int n = Integer.parseInt(i2.getText());
        int n2 = n-1;
        if (n2<=0)n2=0;
        String n3 = String.valueOf(n2);
        i2.setText(n3);
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int int1 = Integer.parseInt(i1.getText());
        int int2 = Integer.parseInt(i2.getText());
        int int3 = Integer.parseInt(i3.getText());
        double ip1 = Double.parseDouble(i1.getText())*2;
        double ip2 = Double.parseDouble(i2.getText())*3.5;
        double ip3 = Double.parseDouble(i3.getText())*6;
        double current = balance.cost;
        balance.cost = current + (ip1+ip2+ip3);
        if (ip1!=0)balance.orders.add("Small Fries - "+int1+"   =   $"+ip1);
        if (ip2!=0)balance.orders.add("Medium Fries - "+int2+"   =   $"+ip2);
        if (ip3!=0)balance.orders.add("Large Fries - "+int3+"   =   $"+ip3);
        balance.inventory = (ArrayList<String>)balance.orders.clone();
        cart c = new cart();
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fries.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fries.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fries.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fries.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fries().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bal;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JTextPane i1;
    private javax.swing.JTextPane i2;
    private javax.swing.JTextPane i3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private java.awt.Panel panel1;
    private java.awt.Panel panel2;
    private javax.swing.JScrollPane scroll;
    // End of variables declaration//GEN-END:variables
}
