/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.oop_final_project2;

//imported this for the background customization - crikee
import javax.swing.ImageIcon;
// import javax.swing.JPanel;
import java.awt.Image;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Color;

/**
 *
 * @author User
 */
public class mainpage extends javax.swing.JFrame {

    /**
     * Creates new form mainpage
     */
    public mainpage() {
        setVisible(true);
        setResizable(false);
        initComponents();
        bal.setText(String.valueOf("Balance: $" + balance.total_balance));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        //declared components or add new here...-crikee
        //check resources folder in OOP_Final_Project2 src folder directory
        panel1 = new BackgroundPanel(getClass().getResource("/com/mycompany/oop_final_project2/resources/pinkBackground.jpg").getPath());

        // panel1 = new java.awt.Panel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        bal = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new StrokeLabel("Menu", Color.BLACK, 2); // Use StrokeLabel with stroke color and width
        jButton14 = new javax.swing.JButton();
        panel2 = new java.awt.Panel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        //Remove the old background color setting, already set in line 39
        // panel1.setBackground(new java.awt.Color(204, 171, 139));
        panel1.setForeground(new java.awt.Color(255, 204, 102));
        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        // jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N, Font Family, Font Bold, Font size
        jLabel1.setFont(new java.awt.Font("Comic Sans MS", java.awt.Font.BOLD, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Foods");
        // jLabel1.setText("Foods");
        panel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 250, 80, -1)); //x-coordinate, y-coordinate, width, height

        // jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setFont(new java.awt.Font("Comic Sans MS", java.awt.Font.BOLD, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Desserts");
        panel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 250, -1, -1));

        // jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setFont(new java.awt.Font("Comic Sans MS", java.awt.Font.BOLD, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Drinks");
        panel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(374, 250, -1, -1));
        panel1.add(filler1, new org.netbeans.lib.awtextra.AbsoluteConstraints(483, 628, -1, -1));

        jButton7.setBackground(new java.awt.Color(255, 234, 144));
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        // Resize the image to fit the button
        //check resources folder in OOP_Final_Project2 src folder directory
        ImageIcon pizzaIcon = new ImageIcon(getClass().getResource("/com/mycompany/oop_final_project2/resources/pizza.png"));
        Image pizzaImage = pizzaIcon.getImage().getScaledInstance(100, 100, Image.SCALE_SMOOTH);
        jButton7.setIcon(new ImageIcon(pizzaImage)); // NOI18N
        // jButton7.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\pizza (1).png")); // NOI18N
        jButton7.setBorder(null);
        jButton7.setFocusPainted(false);
        jButton7.setFocusable(false);
        jButton7.setOpaque(true);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        panel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 110, 110));

        jButton8.setBackground(new java.awt.Color(255, 234, 144));
        // Resize the image to fit the button
        //check resources folder in OOP_Final_Project2 src folder directory
        ImageIcon lemonadeIcon = new ImageIcon(getClass().getResource("/com/mycompany/oop_final_project2/resources/lemonade.png"));
        Image lemonadeImage = lemonadeIcon.getImage().getScaledInstance(110, 110, Image.SCALE_SMOOTH);
        jButton8.setIcon(new ImageIcon(lemonadeImage)); // NOI18N
        // jButton8.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\lemonade (2).png")); // NOI18N
        jButton8.setBorder(null);
        jButton8.setFocusable(false);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        panel1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, 110, 110));

        jButton9.setBackground(new java.awt.Color(255, 234, 144));
        // Resize the image to fit the button
        //check resources folder in OOP_Final_Project2 src folder directory
        ImageIcon cakeIcon = new ImageIcon(getClass().getResource("/com/mycompany/oop_final_project2/resources/cake.png"));
        Image cakeImage = cakeIcon.getImage().getScaledInstance(100, 100, Image.SCALE_SMOOTH);
        jButton9.setIcon(new ImageIcon(cakeImage)); // NOI18N
        // jButton9.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\cake (1).png")); // NOI18N
        jButton9.setBorder(null);
        jButton9.setFocusable(false);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        panel1.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 140, 110, 110));

        jButton13.setBackground(new java.awt.Color(255, 234, 144));
        jButton13.setForeground(new java.awt.Color(255, 234, 144));
        // Resize the image to fit the button
        //check resources folder in OOP_Final_Project2 src folder directory
        ImageIcon cartIcon = new ImageIcon(getClass().getResource("/com/mycompany/oop_final_project2/resources/cart.png"));
        Image cartImage = cartIcon.getImage().getScaledInstance(50, 50, Image.SCALE_SMOOTH);
        jButton13.setIcon(new ImageIcon(cartImage)); // NOI18N
        // jButton13.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\add_14406299 (1).png")); // NOI18N
        jButton13.setBorder(null);
        jButton13.setFocusable(false);
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        panel1.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 30, 60, 60));

        // bal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bal.setFont(new java.awt.Font("Comic Sans MS", java.awt.Font.BOLD, 14)); // NOI18N
        bal.setForeground(new java.awt.Color(255, 255, 255));
        bal.setText("Balance: $0.00");
        panel1.add(bal, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, -1));

        jPanel1.setBackground(new java.awt.Color(153, 102, 0));
        jPanel1.setLayout(new GridBagLayout()); // Use GridBagLayout for centering
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.CENTER;

        // jLabel7.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel7.setFont(new java.awt.Font("Comic Sans MS", java.awt.Font.BOLD, 32)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Menu");
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER); // Center horizontally
        jLabel7.setVerticalAlignment(javax.swing.SwingConstants.CENTER); // Center vertically
        // jLabel7.setText("Food Panter Menu");

        jPanel1.add(jLabel7, gbc); // Add jLabel7 to jPanel1 with constraints

        panel1.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, 130, 60));

        jButton14.setBackground(new java.awt.Color(255, 234, 144));
        jButton14.setForeground(new java.awt.Color(255, 234, 144));
        // Resize the image to fit the button
        //check resources folder in OOP_Final_Project2 src folder directory
        ImageIcon inventoryIcon = new ImageIcon(getClass().getResource("/com/mycompany/oop_final_project2/resources/inventory.png"));
        Image inventoryImage = inventoryIcon.getImage().getScaledInstance(50, 50, Image.SCALE_SMOOTH);
        jButton14.setIcon(new ImageIcon(inventoryImage)); // NOI18N
        // jButton14.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\paper-bag (1) (1).png")); // NOI18N
        jButton14.setBorder(null);
        jButton14.setFocusable(false);
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        panel1.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 60, 60));

        getContentPane().add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 780, 360));

        panel2.setBackground(new java.awt.Color(153, 102, 0));

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 820, Short.MAX_VALUE)
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        getContentPane().add(panel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        Foods f = new Foods();
        setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        desserts d = new desserts();
        setVisible(false);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        drinks dr = new drinks();
        setVisible(false);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        cart c = new cart();
        setVisible(false);
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        inventory in = new inventory();
        setVisible(false);
    }//GEN-LAST:event_jButton14ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainpage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bal;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    // private java.awt.Panel panel1;
    private BackgroundPanel panel1; // Use BackgroundPanel instead of java.awt.Panel
    private java.awt.Panel panel2;
    // End of variables declaration//GEN-END:variables
}
